const fs = require('fs');
const books = JSON.parse(fs.readFileSync('data/books.json', 'utf8'));

const coverMap = {
  'pride-and-prejudice': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'alice-in-wonderland': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'the-adventures-of-tom-sawyer': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'a-christmas-carol': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'the-wizard-of-oz': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'peter-pan': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'the-jungle-book': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'frankenstein': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'the-time-machine': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'the-war-of-the-worlds': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'twenty-thousand-leagues': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'journey-to-the-center-of-the-earth': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'dracula': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'the-odyssey': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'the-art-of-war': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'the-history-of-the-decline-and-fall': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'a-tale-of-two-cities': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'the-last-of-the-mohicans': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'the-republic': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'beyond-good-and-evil': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'meditations': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'the-prince': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'on-the-origin-of-species': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'a-brief-history-of-time': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'the-selfish-gene': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'silent-spring': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'the-autobiography-of-benjamin-franklin': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'narrative-of-the-life-of-frederick-douglass': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'the-story-of-my-life': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'wuthering-heights': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'jane-eyre': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'great-expectations': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'the-picture-of-dorian-gray': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'the-importance-of-being-earnest': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'treasure-island': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'the-strange-case-of-dr-jekyll': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'moby-dick': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'the-adventures-of-sherlock-holmes': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'the-invisible-man': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'anne-of-green-gables': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'the-secret-garden': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'black-beauty': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'the-wind-in-the-willows': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'heart-of-darkness': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'the-call-of-the-wild': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'white-fang': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'the-great-gatsby': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'the-scarlet-letter': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'the-turn-of-the-screw': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'around-the-world-in-eighty-days': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'the-count-of-monte-cristo': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'les-miserables': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'the-three-musketeers': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'don-quixote': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'the-divine-comedy': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'metamorphosis': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'the-old-man-and-the-sea': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'animal-farm': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  '1984': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'the-little-prince': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'charlottes-web': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'the-giver': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'a-wrinkle-in-time': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'the-hobbit': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'fahrenheit-451': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'brave-new-world': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'the-catcher-in-the-rye': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'to-kill-a-mockingbird': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'the-outsiders': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'hatchet': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'holes': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'tuesdays-with-morrie': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'who-moved-my-cheese': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'the-alchemist': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
  'the-kite-runner': 'https://covers.openlibrary.org/b/id/8268416-L.jpg',
  'life-of-pi': 'https://covers.openlibrary.org/b/id/6976526-L.jpg',
  'the-maze-runner': 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
  'the-hunger-games': 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
  'dune': 'https://covers.openlibrary.org/b/id/8231996-L.jpg',
  'enders-game': 'https://covers.openlibrary.org/b/id/7886226-L.jpg',
};

const updated = books.map(book => ({
  ...book,
  coverUrl: coverMap[book.id] || book.coverUrl || null,
}));

fs.writeFileSync('data/books.json', JSON.stringify(updated, null, 2));
const withCovers = updated.filter(b => b.coverUrl).length;
console.log('Updated', updated.length, 'books,', withCovers, 'with cover URLs');
