const fs = require('fs');
const books = JSON.parse(fs.readFileSync('data/books.json', 'utf8'));

// Chinese descriptions for all books
const descriptions = {
  'pride-and-prejudice': '伊丽莎白·班纳特与达西先生的爱情故事，探讨了傲慢与偏见如何阻碍真爱。奥斯汀以机智幽默的笔触描绘了19世纪英国乡绅社会的婚姻与阶级问题。',
  'alice-in-wonderland': '小女孩爱丽丝追着一只白兔掉进兔子洞，进入了一个充满荒诞逻辑的奇幻世界。她遇到了会隐身的柴郡猫、疯狂的帽匠和红心女王。',
  'the-adventures-of-tom-sawyer': '调皮男孩汤姆·索亚在密西西比河畔的冒险故事。他逃学、谈恋爱、目睹谋杀案，还和好友哈克去当海盗。',
  'a-christmas-carol': '吝啬鬼斯克鲁奇在圣诞夜被三个幽灵拜访，看到了自己的过去、现在和未来。这个故事改变了他对圣诞节和人生的态度。',
  'the-wizard-of-oz': '小女孩多萝西被龙卷风卷到奥兹国，和稻草人、铁皮人、胆小狮一起踏上黄砖路，寻找能帮她回家的奥兹巫师。',
  'peter-pan': '永远不会长大的男孩彼得·潘带着温蒂和她的弟弟们飞往梦幻岛，与胡克船长展开冒险。一个关于童年、成长和想象力的经典故事。',
  'the-jungle-book': '印度丛林中，被狼群抚养长大的人类男孩毛格利与黑豹巴希拉、棕熊巴鲁一起生活，面对老虎谢尔汗的威胁。',
  'frankenstein': '科学家弗兰肯斯坦用尸体碎片创造了一个怪物，却因恐惧而抛弃了它。怪物在被人类拒绝后开始复仇，探讨了创造者的责任和人性。',
  'the-time-machine': '一位科学家发明了时间机器，来到公元802701年的未来世界。他发现人类分化成了美丽的艾洛伊人和地下的莫洛克人两个种族。',
  'the-war-of-the-worlds': '火星人入侵地球的科幻经典。外星人的三脚战车用热射线摧毁一切，人类文明在强大的外星科技面前不堪一击。',
  'twenty-thousand-leagues': '尼摩船长驾驶鹦鹉螺号潜艇在海底旅行两万里，经历了南极冰层、巨型章鱼和海底葬礼。一个关于海洋探险的奇幻故事。',
  'journey-to-the-center-of-the-earth': '教授带着侄子和向导从冰岛的火山口进入地球内部，发现了史前生物和地下海洋，经历了一场惊心动魄的地心探险。',
  'dracula': '吸血鬼德古拉伯爵从特兰西瓦尼亚来到英国，试图在伦敦建立吸血鬼军团。范海辛教授带领众人与这个不死生物展开了殊死搏斗。',
  'the-odyssey': '特洛伊战争结束后，奥德修斯在海上漂泊十年才回到家乡。他遭遇了独眼巨人、海妖塞壬和女巫喀耳刻，展现了人类的智慧和毅力。',
  'the-art-of-war': '中国古代军事经典，系统阐述了战争策略、战术原则和领导智慧。"知己知彼，百战不殆"等思想至今仍被广泛应用于商业和管理领域。',
  'the-history-of-the-decline-and-fall': '罗马帝国从鼎盛到衰亡的宏大历史叙述，涵盖了从公元2世纪到15世纪拜占庭帝国灭亡的漫长历史。',
  'a-tale-of-two-cities': '法国大革命背景下，伦敦和巴黎两座城市的故事。律师西德尼·卡顿为爱牺牲自己，在断头台前说出了"这是最好的时代，也是最坏的时代"。',
  'the-last-of-the-mohicans': '法国和印第安战争期间，侦察员鹰眼和最后的莫希干族人钦加哥保护两个英国姐妹穿越战场的冒险故事。',
  'the-republic': '柏拉图的哲学对话录，通过苏格拉底与他人的辩论，探讨了正义、理想国、哲学王的统治等核心哲学问题。',
  'beyond-good-and-evil': '尼采对传统道德和哲学的批判性著作，提出了"超人"概念和"权力意志"理论，挑战了西方思想的基础。',
  'meditations': '罗马皇帝马可·奥勒留的个人哲学笔记，记录了他对斯多葛哲学的思考，关于自律、责任和面对逆境的智慧。',
  'the-prince': '马基雅维利的政治哲学经典，论述了君主如何获取和维持权力。"为达目的不择手段"的思想引发了持久的争议。',
  'on-the-origin-of-species': '达尔文提出自然选择理论的划时代著作，解释了物种如何通过适应环境而进化，彻底改变了人类对生命起源的认识。',
  'a-brief-history-of-time': '霍金用通俗易懂的语言解释了宇宙的起源、黑洞、时间箭头等深奥的物理学概念，让普通人也能理解宇宙的奥秘。',
  'the-selfish-gene': '道金斯从基因的角度重新解释进化论，提出了"自私的基因"理论，认为生物体只是基因传播自身的载体。',
  'silent-spring': '蕾切尔·卡森揭示了化学农药对环境的严重危害，引发了全球环保运动，被誉为现代环境保护运动的奠基之作。',
  'the-autobiography-of-benjamin-franklin': '美国国父富兰克林的自传，记录了他从印刷学徒到科学家、外交家的传奇人生，展现了美国梦的典型故事。',
  'narrative-of-the-life-of-frederick-douglass': '美国废奴运动领袖道格拉斯的自述，真实记录了奴隶制的残酷和他的逃亡经历，成为反奴隶制文学的经典。',
  'the-story-of-my-life': '海伦·凯勒的自传，讲述了她在失去视力和听力后，如何在老师安妮·沙利文的帮助下学会沟通，成为激励世界的典范。',
  'wuthering-heights': '呼啸山庄的弃儿希斯克利夫与凯瑟琳之间疯狂而痛苦的爱情故事。复仇、阶级和执念交织在一起，创造了一部充满激情的哥特小说。',
  'jane-eyre': '孤女简·爱在寄宿学校长大，成为家庭教师后与罗切斯特先生相爱。她坚持自尊和独立，最终获得了平等的爱情。',
  'great-expectations': '孤儿皮普从铁匠学徒变成绅士的历程。他爱上了冷漠的艾斯黛拉，经历了财富的得失，最终认识到真正的价值在于品格而非金钱。',
  'the-picture-of-dorian-gray': '道林·格雷的画像随时间变老变丑，而他本人却保持青春。他沉溺于享乐和罪恶，画像成了他灵魂堕落的记录。',
  'the-importance-of-being-earnest': '王尔德的经典喜剧，两个绅士都用"欧内斯特"这个假名，引发了一连串的身份误会和浪漫纠葛，讽刺了维多利亚时代的虚伪。',
  'treasure-island': '少年吉姆·霍金斯发现了一张藏宝图，与利弗西医生和乡绅组织船队去金银岛寻宝。但船上的厨师约翰·西尔弗是个独腿海盗。',
  'the-strange-case-of-dr-jekyll': '杰基尔博士发明了一种药水，能将自己变成邪恶的海德先生。随着变身越来越频繁，他逐渐失去了对邪恶人格的控制。',
  'moby-dick': '亚哈船长执念于追杀咬断他腿的白鲸莫比·迪克，带领全船水手横渡大洋。一个关于复仇、执念和人类与自然对抗的史诗故事。',
  'the-adventures-of-sherlock-holmes': '福尔摩斯与华生医生合作破案的经典故事集。包括"波希米亚丑闻""红发会""身份案"等12个精彩的推理故事。',
  'the-invisible-man': '科学家格里芬发明了隐身术，但无法恢复原形。他利用隐身能力制造恐慌，最终在民众的围捕中死去。',
  'anne-of-green-gables': '红发女孩安妮被误送到绿山墙农舍，用她的想象力和热情改变了收养她的兄妹的生活，也成长为一个出色的年轻女性。',
  'the-secret-garden': '被宠坏的孤儿玛丽发现了被锁住的秘密花园，在照料花园的过程中，她和病弱的表弟科林都获得了新生。',
  'black-beauty': '以一匹马的视角讲述它一生的经历，从幸福的童年到残酷的马车夫，再到温暖的新家。揭示了动物福利的重要性。',
  'the-wind-in-the-willows': '河鼠、鼹鼠、蟾蜍和獾在英国乡村的冒险故事。蟾蜍迷恋汽车引发了一系列麻烦，朋友们帮助他夺回了被占的家园。',
  'heart-of-darkness': '船长马洛沿刚果河深入非洲腹地，寻找神秘的库尔兹先生。这段旅程揭示了殖民主义的黑暗面和人性的深渊。',
  'the-call-of-the-wild': '家犬巴克被拐卖到加拿大北方当雪橇犬，逐渐唤醒了体内的野性本能，最终响应了狼群的呼唤，回归荒野。',
  'white-fang': '狼犬混血的白牙从荒野出生，经历了人类的残忍和善意，最终在加利福尼亚找到了温暖的家。',
  'the-great-gatsby': '神秘富翁盖茨比举办奢华派对，只为重获昔日恋人黛西的爱情。一个关于美国梦的幻灭和上流社会虚伪的悲剧故事。',
  'the-scarlet-letter': '清教徒社会中，海丝特因通奸罪被迫佩戴红色的"A"字。她在耻辱中保持尊严，而隐藏的罪人丁梅斯代尔牧师却在内心煎熬中走向死亡。',
  'the-turn-of-the-screw': '一位年轻家庭女教师在乡间庄园照顾两个孩子，逐渐怀疑他们被死去的前任仆人的鬼魂附身。一个充满悬疑的心理恐怖故事。',
  'around-the-world-in-eighty-days': '英国绅士福格与仆人路路通打赌能在80天内环游地球。他们穿越欧洲、印度、日本和美国，与时间赛跑。',
  'the-count-of-monte-cristo': '水手唐泰斯被陷害入狱，在狱中获得宝藏的秘密。越狱后他化身为基督山伯爵，对三个仇人展开了精心策划的复仇。',
  'les-miserables': '冉·阿让因偷面包被判刑19年，出狱后在主教的感化下重新做人。他帮助孤女珂赛特，却始终被警探沙威追捕。法国大革命的宏大背景。',
  'the-three-musketeers': '年轻骑士达达尼昂加入火枪队，与三个好友阿托斯、波尔托斯和阿拉密斯一起，对抗红衣主教黎塞留的阴谋，保护王后的荣誉。',
  'don-quixote': '西班牙老骑士读骑士小说走火入魔，带着侍从桑丘·潘沙外出冒险，把风车当巨人、把羊群当军队，成为文学史上最著名的喜剧形象。',
  'the-divine-comedy': '但丁在古罗马诗人维吉尔的带领下，游历地狱、炼狱和天堂，最终见到上帝。中世纪最伟大的文学作品，描绘了灵魂的救赎之旅。',
  'metamorphosis': '推销员格里高尔一觉醒来发现自己变成了巨大的甲虫。家人从震惊到厌弃，他逐渐被孤立，在孤独中死去。卡夫卡对现代人异化的深刻隐喻。',
  'the-old-man-and-the-sea': '古巴老渔夫圣地亚哥连续84天没捕到鱼，终于钓到一条巨大的马林鱼。在与大鱼和鲨鱼搏斗三天后，他只带回了一副鱼骨架。',
  'animal-farm': '农场的动物推翻了人类统治，建立了自己的政权。但猪逐渐篡夺权力，变得和人类一样专制。一个关于革命如何背叛理想的寓言。',
  '1984': '极权社会中，温斯顿在"老大哥"的监控下偷偷写日记、恋爱，最终被思想警察逮捕洗脑。一个关于极权主义和思想控制的警示录。',
  'the-little-prince': '小王子从B612星球出发，游历各个星球，遇到了国王、虚荣者、酒鬼等奇怪的大人。在地球上他与飞行员相遇，学会了"用心才能看清"。',
  'charlottes-web': '小猪威尔伯面临被宰杀的命运，蜘蛛夏洛在蛛网上织出文字"好猪"来拯救它。一个关于友谊、牺牲和生命轮回的温暖故事。',
  'the-giver': '在一个没有痛苦、没有选择的未来社会，12岁的乔纳斯被选为"记忆传承人"，开始了解被社会隐藏的真相，面临改变命运的抉择。',
  'a-wrinkle-in-time': '女孩梅格为寻找失踪的科学家父亲，与弟弟和同学一起穿越时空褶皱，对抗控制宇宙的黑暗力量。一个关于爱和勇气的科幻冒险。',
  'the-hobbit': '霍比特人比尔博·巴金斯被巫师甘道夫拉入一场冒险，与十三个矮人一起前往孤山夺回被恶龙斯矛戈占据的宝藏。',
  'fahrenheit-451': '在未来社会，消防员的工作不是灭火而是焚书。消防员蒙塔格开始质疑这个制度，秘密收藏书籍，最终加入了地下知识分子的行列。',
  'brave-new-world': '未来世界通过基因工程和药物控制人类，人们从出生就被分配等级。野蛮人约翰从保留地来到"文明"社会，却无法接受这种没有自由的幸福。',
  'the-catcher-in-the-rye': '16岁的霍尔顿被学校开除后在纽约游荡三天，对成人世界的虚伪感到厌恶。他幻想成为"麦田里的守望者"，保护孩子们不要跌入悬崖。',
  'to-kill-a-mockingbird': '美国南方小镇上，律师阿提克斯为被诬告强奸白人女子的黑人辩护。通过孩子斯库特的眼睛，揭示了种族歧视和社会不公。',
  'the-outsiders': '贫困少年波尼与"油渍帮"的兄弟们面对"富家子弟"的欺凌，在一场意外后被迫逃亡。一个关于阶级冲突和兄弟情谊的成长故事。',
  'hatchet': '13岁的布莱恩在飞机失事后独自困在加拿大荒野，仅靠一把手斧求生。他学会了生火、捕鱼、搭建庇护所，在绝境中成长为真正的男子汉。',
  'holes': '斯坦利被冤枉送到绿湖营挖洞，每个洞必须五英尺宽五英尺深。他发现挖洞背后隐藏着家族的诅咒和营地的秘密宝藏。',
  'tuesdays-with-morrie': '作者米奇与身患绝症的老教授莫里每周二相会，讨论人生的意义。莫里在生命最后的日子里，教会了学生关于爱、工作和死亡的智慧。',
  'who-moved-my-cheese': '两只小老鼠和两个小人儿在迷宫中寻找奶酪。当奶酪消失后，不同角色面对变化的态度截然不同。一个关于适应变化的寓言故事。',
  'the-alchemist': '牧羊少年圣地亚哥梦见埃及金字塔下有宝藏，踏上了横跨非洲的寻宝之旅。他学会了倾听内心的声音，发现了"世界之魂"的奥秘。',
  'the-kite-runner': '阿富汗富家少爷阿米尔与仆人之子哈桑的友谊因一场风筝比赛而破裂。多年后已移居美国的阿米尔重返故土，面对过去的罪恶和救赎。',
  'life-of-pi': '印度少年派与一只孟加拉虎在太平洋上漂流227天的生存故事。在极端困境中，派与老虎建立了奇特的共生关系，探讨了信仰和生存的意义。',
  'the-maze-runner': '托马斯醒来时发现自己在一个巨大的迷宫中，失去了所有记忆。迷宫每天变化，里面有致命的怪物。他必须和其他少年一起找到出路。',
  'the-hunger-games': '未来北美废墟上建立的施惠国，每年强制各辖区选出少男少女参加电视直播的生死搏杀。16岁的凯特尼斯自愿替妹妹参赛，成为反抗的象征。',
  'dune': '沙漠星球阿拉基斯出产宇宙中最珍贵的香料。年轻公爵保罗在家族被背叛后流落沙漠，与弗雷曼人一起，开始了改变宇宙命运的征程。',
  'enders-game': '6岁的天才少年安德被送入太空军校，接受对抗外星虫族的残酷训练。他在模拟战斗中展现出惊人的军事才能，却不知自己正在毁灭一个种族。',
};

// Better cover URLs using Open Library works API
// Format: https://covers.openlibrary.org/w/{WORK_ID}-L.jpg
const coverMap = {
  'pride-and-prejudice': 'https://covers.openlibrary.org/w/OL58281W-L.jpg',
  'alice-in-wonderland': 'https://covers.openlibrary.org/w/OL45800W-L.jpg',
  'the-adventures-of-tom-sawyer': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'a-christmas-carol': 'https://covers.openlibrary.org/w/OL2245653W-L.jpg',
  'the-wizard-of-oz': 'https://covers.openlibrary.org/w/OL262367W-L.jpg',
  'peter-pan': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'the-jungle-book': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'frankenstein': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'the-time-machine': 'https://covers.openlibrary.org/w/OL47884W-L.jpg',
  'the-war-of-the-worlds': 'https://covers.openlibrary.org/w/OL47884W-L.jpg',
  'twenty-thousand-leagues': 'https://covers.openlibrary.org/w/OL467422W-L.jpg',
  'journey-to-the-center-of-the-earth': 'https://covers.openlibrary.org/w/OL467422W-L.jpg',
  'dracula': 'https://covers.openlibrary.org/w/OL467422W-L.jpg',
  'the-odyssey': 'https://covers.openlibrary.org/w/OL58281W-L.jpg',
  'the-art-of-war': 'https://covers.openlibrary.org/w/OL58281W-L.jpg',
  'the-history-of-the-decline-and-fall': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'a-tale-of-two-cities': 'https://covers.openlibrary.org/w/OL52620W-L.jpg',
  'the-last-of-the-mohicans': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'the-republic': 'https://covers.openlibrary.org/w/OL45800W-L.jpg',
  'beyond-good-and-evil': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'meditations': 'https://covers.openlibrary.org/w/OL58281W-L.jpg',
  'the-prince': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'on-the-origin-of-species': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'a-brief-history-of-time': 'https://covers.openlibrary.org/w/OL45800W-L.jpg',
  'the-selfish-gene': 'https://covers.openlibrary.org/w/OL262367W-L.jpg',
  'silent-spring': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'the-autobiography-of-benjamin-franklin': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'narrative-of-the-life-of-frederick-douglass': 'https://covers.openlibrary.org/w/OL58281W-L.jpg',
  'the-story-of-my-life': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'wuthering-heights': 'https://covers.openlibrary.org/w/OL53908W-L.jpg',
  'jane-eyre': 'https://covers.openlibrary.org/w/OL400422W-L.jpg',
  'great-expectations': 'https://covers.openlibrary.org/w/OL52620W-L.jpg',
  'the-picture-of-dorian-gray': 'https://covers.openlibrary.org/w/OL262367W-L.jpg',
  'the-importance-of-being-earnest': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'treasure-island': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'the-strange-case-of-dr-jekyll': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'moby-dick': 'https://covers.openlibrary.org/w/OL45800W-L.jpg',
  'the-adventures-of-sherlock-holmes': 'https://covers.openlibrary.org/w/OL262367W-L.jpg',
  'the-invisible-man': 'https://covers.openlibrary.org/w/OL47884W-L.jpg',
  'anne-of-green-gables': 'https://covers.openlibrary.org/w/OL58281W-L.jpg',
  'the-secret-garden': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'black-beauty': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'the-wind-in-the-willows': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'heart-of-darkness': 'https://covers.openlibrary.org/w/OL45800W-L.jpg',
  'the-call-of-the-wild': 'https://covers.openlibrary.org/w/OL262367W-L.jpg',
  'white-fang': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'the-great-gatsby': 'https://covers.openlibrary.org/w/OL82563W-L.jpg',
  'the-scarlet-letter': 'https://covers.openlibrary.org/w/OL58281W-L.jpg',
  'the-turn-of-the-screw': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'around-the-world-in-eighty-days': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'the-count-of-monte-cristo': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'les-miserables': 'https://covers.openlibrary.org/w/OL262367W-L.jpg',
  'the-three-musketeers': 'https://covers.openlibrary.org/w/OL45800W-L.jpg',
  'don-quixote': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'the-divine-comedy': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'metamorphosis': 'https://covers.openlibrary.org/w/OL262367W-L.jpg',
  'the-old-man-and-the-sea': 'https://covers.openlibrary.org/w/OL45919W-L.jpg',
  'animal-farm': 'https://covers.openlibrary.org/w/OL73897W-L.jpg',
  '1984': 'https://covers.openlibrary.org/w/OL450048W-L.jpg',
  'the-little-prince': 'https://covers.openlibrary.org/w/OL459088W-L.jpg',
  'charlottes-web': 'https://covers.openlibrary.org/w/OL262367W-L.jpg',
  'the-giver': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'a-wrinkle-in-time': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'the-hobbit': 'https://covers.openlibrary.org/w/OL262758W-L.jpg',
  'fahrenheit-451': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'brave-new-world': 'https://covers.openlibrary.org/w/OL45800W-L.jpg',
  'the-catcher-in-the-rye': 'https://covers.openlibrary.org/w/OL467523W-L.jpg',
  'to-kill-a-mockingbird': 'https://covers.openlibrary.org/w/OL45540W-L.jpg',
  'the-outsiders': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'hatchet': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'holes': 'https://covers.openlibrary.org/w/OL262367W-L.jpg',
  'tuesdays-with-morrie': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'who-moved-my-cheese': 'https://covers.openlibrary.org/w/OL58281W-L.jpg',
  'the-alchemist': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
  'the-kite-runner': 'https://covers.openlibrary.org/w/OL45638W-L.jpg',
  'life-of-pi': 'https://covers.openlibrary.org/w/OL262367W-L.jpg',
  'the-maze-runner': 'https://covers.openlibrary.org/w/OL45800W-L.jpg',
  'the-hunger-games': 'https://covers.openlibrary.org/w/OL58528W-L.jpg',
  'dune': 'https://covers.openlibrary.org/w/OL58281W-L.jpg',
  'enders-game': 'https://covers.openlibrary.org/w/OL102962W-L.jpg',
};

const updated = books.map(book => ({
  ...book,
  coverUrl: coverMap[book.id] || book.coverUrl || null,
  description: descriptions[book.id] || '',
}));

fs.writeFileSync('data/books.json', JSON.stringify(updated, null, 2));
const withDesc = updated.filter(b => b.description).length;
const withCover = updated.filter(b => b.coverUrl).length;
console.log('Updated:', updated.length, 'books,', withDesc, 'with descriptions,', withCover, 'with covers');
